name: pm_ajay
description: PM-AJAY Government Project Management System - A Flutter application for tracking implementing and executing agencies, fund flow, and project monitoring.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^3.0.0

  # Navigation
  go_router: ^12.1.3

  # Database
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # API & Network
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  connectivity_plus: ^5.0.2
  socket_io_client: ^2.0.3+1
  
  # Real-time & WebSocket
  firebase_database: ^11.1.4
  web_socket_channel: ^2.4.0

  # Authentication
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  local_auth: ^2.1.7

  # Notifications & Communication
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^16.3.0
  mailer: ^6.0.1

  # Analytics & Monitoring
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3

  # Charts & Visualization
  fl_chart: ^0.65.0
  syncfusion_flutter_charts: ^24.1.41
  syncfusion_flutter_datepicker: ^24.1.41

  # Maps & Geolocation
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # Core utilities
  equatable: ^2.0.5

  # Blockchain (simplified for now - can be added back after resolving conflicts)
  # web3dart: ^2.7.3
  # bip39: ^1.0.6
  # ed25519_hd_key: ^2.2.0

  # PDF & File Handling
  pdf: ^3.10.7
  printing: ^5.11.1
  file_picker: ^6.1.1
  open_file: ^3.3.2
  path: ^1.8.3

  # Voice & Speech
  speech_to_text: ^6.5.1
  flutter_tts: ^3.8.5

  # Utilities
  intl: ^0.18.1
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  image_picker: ^1.0.5
  permission_handler: ^11.1.0
  crypto: ^3.0.3
  encrypt: ^5.0.3
  
  # Form Validation
  formz: ^0.6.1
  
  # Data Processing
  collection: ^1.18.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  hive_generator: ^2.0.1

  # Linting
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/

  # fonts:
  #   - family: CustomIcons
  #     fonts:
  #       - asset: assets/fonts/CustomIcons.ttf